### ISSUE TITLE
Should have tool for daily status email/notification

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#160]
We don't want to implement this ourselves, but there should be packages out there that will take a pulse of the system and send it out in the form of an email message.

Should  also warn if disk/memory/CPU usage becomes worrisome.

**Comment by webbpinner** [comment]
Many of the ship’s I’ve sailed on have implemented systems that do this.  Some are commercial products, some are home grown.

-W


=-------------------------------------------------=
Webb Pinner
Mobile: 401.749.9322
Email: webbpinner@gmail.com
Website: http://www.oceandatarat.org

**Comment by davidpablocohn** [comment]
Offloading this to telegraf + influxdb + grafana
