### ISSUE TITLE
Non-Highcharts line widget

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#166]
The Highcharts line widgets are great, and free licenses are available for academic institutions,  but they are not open source.

**Comment by MignonBelongie** [comment]
I can take a shot at a D3 based TimelineWidget. I don't have any prior experience with D3, but I've been playing around with it for a few days, and I now have a very rough implementation of a TimelineWidget working with WidgetServer.

**Comment by vwarner1411** [comment]
I wrote a bunch of D3 based stuff for the das a few years back. It should
all exist still. I can dig it out if it’s not on my github. @vwarner1411

**Comment by MignonBelongie** [comment]
Thanks, I'll look at it. I actually came across some helpful code of yours today in stackoverflow, too.

**Comment by davidpablocohn** [comment]
That would be great - thank you!

**Comment by davidpablocohn** [comment]
At RVTEC - several people suggested looking at Rickshaw (https://tech.shutterstock.com/rickshaw/examples/), which is open source, apparently built on top of D3. Might be worth a look.

**Comment by MignonBelongie** [comment]
I have something ready to demo, but I just tried pushing, and it looks like I don't have permission any more.

**Comment by davidpablocohn** [comment]
I just tried adding you. Can you try sending a pull request?
