### ISSUE TITLE
Non-Highcharts Dial widget

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#167]
The Highcharts line widgets are great, and free licenses are available for academic institutions, but they are not open source.

**Comment by davidpablocohn** [comment]
There's something that might be a good starting point here: http://bl.ocks.org/tomerd/1499279

**Comment by MignonBelongie** [comment]
I found that yesterday and played around with it a bit, and it looks good. It shouldn't take too much more work to finish the styling and make it work with WidgetServer.
