### ISSUE TITLE
Add ability to define a custom suffix for log files

### ISSUE THREAD

**Issue by webbpinner** [OceanDataTools/openrvdas#188]
Would like the ability to define a custom suffix for log files.  Currently the filenames created via logfile_writer do not have a file extension and simply terminate after the timestamp.  Adding the ability to define a time stamp enables the user to add additional text after the timestamp as well as the ability to specify a file extension.

**Comment by davidpablocohn** [comment]
Fixed in b24c96db8b4b4c3953157cf329d32918af59edff
