### ISSUE TITLE
writer for pushing data to InfluxDB

### ISSUE THREAD

**Issue by webbpinner** [OceanDataTools/openrvdas#192]
add ability for OpenRVDAS to write data to InfluxDB.

**Comment by webbpinner** [comment]
Did something change with how writers are initialized?  I'm trying to verify the writer works on the master branch but so far no luck.  I can't even get OpenRVDAS to show a print statement in the init block of the InfluxDB writer.

I did find a rather large change in the NBP_1406_cruise.yaml between the version I was developing against vs the version I got when I checked out the official repo post-merge

**Comment by davidpablocohn** [comment]
Resolved with creation of logger/writers/influxdb_writer.py
