### ISSUE TITLE
Unify installation scripts into single script

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#245]
Right now, we've got three arch-dependent installations scripts for OpenRVDAS: build_openrvdas_[centos7,ubuntu18,macos]. The install_influxdb script is an example of detecting the installed distribution/OS and doing the right thing. It would be desirable to combine the three build_* scripts into a single install_openrvdas.sh script that operates the same way.

**Comment by webbpinner** [comment]
while not the same as a unified script... what about using the system's package managers (yarn, apt, brew)??

**Comment by davidpablocohn** [comment]
We do that inside the script, but each system uses a different package
manager, and some of the things we need to install don’t have packages
already built in the versions we need. Which is what makes each install
script complicated. For example, CentOS7 Doesn’t have the right version of
python or Django, so we have to install those separately.

**Comment by davidpablocohn** [comment]
Note: while doing this, also move Python packages into a requirements.txt file

**Comment by davidpablocohn** [comment]
Merged to dev.
