### ISSUE TITLE
Flag to tell simulate_data.py what permissions simulated ports should have

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#269]
Add a --mod (for 'chmod') or other appropriately-named flag to tell simulate_data.py that simulated ports should be created with 777 or some other  access permissions.

**Comment by webbpinner** [comment]
Given that the simulated ports are for testing purposes and not production, is there any harm in setting the ports to 777 by default?

**Comment by davidpablocohn** [comment]
This turns out to be a non-issue. Normally, the simulated_data.py etc scripts are going to be run by the same uid (rvdas) as the processes trying to read.
