### ISSUE TITLE
Use python's pty library instead of `socat` for data simulation

### ISSUE THREAD

**Issue by KPed-at-home** [OceanDataTools/openrvdas#277]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
Instead of delegating to socat for the virtual serial ports for data simulation, use python's pty library (https://docs.python.org/3.8/library/pty.html).  I just have this fetish where I think it's better to write python in python (not shell).

**Describe alternatives you've considered**
Another alternative might be to use RFC2217 serial ports (https://pyserial.readthedocs.io/en/latest/examples.html), but I've only used that from one box to another.  And it is marked as experimental, so I'd hesitate to incorporate it into a curated product.

**Comment by davidpablocohn** [comment]
KPed - Thanks for all of these! At the moment I'm focusing on #283, which appears to be the biggest villain in several ways. If you've got time, would you be willing to take this one up?

**Comment by KPed-at-home** [comment]
I'll look at it.  Thanks.

**Comment by davidpablocohn** [comment]
Merged issue_277 into dev
