### ISSUE TITLE
Timestamps in /var/log/openrvdas/*.stderr are weird

### ISSUE THREAD

**Issue by KPed-at-home** [OceanDataTools/openrvdas#282]
**Describe the bug**
Looks like the milliseconds are repeated.

**To Reproduce**
See any /var/log/openrvdas/*.stderr file.

**Expected behavior**
milliseconds not repeated.

**Desktop (please complete the following information):**
 - RHEL7, CentOS7, Raspbian 10 (buster)

**Comment by davidpablocohn** [comment]
There's a little bit of a remaining mess: For some reason, stderr to the files includes msec by default:
````
2021-08-04 15:47:59,991Z 20 INFO cached_data_writer.py:88 CachedDataWriter trying to connect to localhost:8766
````
but stderr to the console does not:
```
2021-08-04T16:11:18Z 30 WARNING record_parser.py:373 No formats matched field_string "+020.53,60,01"
```
They're both going through the same formatter, but it means that they're getting their time strings from different places. For now, we'll just go with the current situations.
