### ISSUE TITLE
InfluxDB supervisor task ignores config.toml

### ISSUE THREAD

**Issue by webbpinner** [OceanDataTools/openrvdas#334]
With the current install script for influxDB on Ubuntu 22.04 the influxd serivce ignores the settings specified in the default infludb config.toml file.  This is because the supervisor task does not pass the location of the default influxDB configuration file (`/etc/influxdb/config.toml`).

This is important on VM-base installations where the root filesystem is intentionally small.  The default location of the database is `/home/<user>/.influxdb` thus on VM-based installations InfluxDB can quickly fill up the filesystem.  The config.toml can be used to tell influxd the desired location of the database files.

This can be easily fixed by adding an `environment` argument to the supervisor task definition in: `/etc/supervisor/conf.d/influxdb.conf`.  This will cause the influx daemon to read/use the locations specified in `/etc/influxdb/config.yaml`

```
; Run InfluxDB
[program:influxdb]
command=/usr/bin/influxd --reporting-disabled
directory=/opt/openrvdas
environment=INFLUXD_CONFIG_PATH=/etc/influxdb
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/openrvdas/influxdb.stderr
user=rvdas
```

Optionally, the installer should be prompted to specify a storage location during the installation process.

**Comment by davidpablocohn** [comment]
It'll need a slight tweak for MacOS, where things get put into /usr/local/etc instead of /etc
