### ISSUE TITLE
Updated NMEATransform may break existing logger configs

### ISSUE THREAD

**Issue by webbpinner** [OceanDataTools/openrvdas#369]
**Describe the bug**
The updated NMEATransform API breaks the logger configs for users using the previous API.

Here is the error:
```
2024-04-06T10:46:37Z 50 CRITICAL logger_runner.py:161 Config for true_wind_log->file: Class "ComposedWriter": Class NMEATransform: NMEATransform.__init__() missing 1 required positional argument: 'nmea_list'
Class definition: {'class': 'NMEATransform', 'kwargs': {'mwd_talker_id': 'PFMWD', 'true_wind_dir_field': 'FM_TrueWindDir', 'true_wind_speed_kt_field': 'FM_TrueWindSpd'}} 
```

Propose updating the NMEATransform to make 'nmea_list' and optional positional argument (i.e. default value = []).  Hopefully this will prevent existing logger configs from breaking after updating OpenRVDAS.

**Comment by davidpablocohn** [comment]
Fixed and integrated...
