### ISSUE TITLE
MQTTWriter breaks with new MQTT

### ISSUE THREAD

**Issue by davidpablocohn** [OceanDataTools/openrvdas#395]
From Lilly Petersen:

Hey Pablo,

 

I know you’re busy so no need to respond right away, but I though I’d let you know of an issue I found with the MQTTWriter. I get the following error for pahoMQTT versions 2 and up:

2024-07-18T16:37:51Z 50 CRITICAL logger_runner.py:165 Config for bwnc_file->net/mqtt: Class "ComposedWriter": Class MQTTWriter: Unsupported callback API version: version 2.0 added a callback_api_version, see docs/migrations.rst for details

 

Apparently they made API breaking changes in version 2 which came out in February (See https://eclipse.dev/paho/files/paho.mqtt.python/html/migrations.html)

I’ve tried with version many versions below 2.0, but the MQTT writer just freezes all writer output for that config (I think it’s getting itself into an infinite loop).

 
I modified the code so it’s only making one call to pahomqtt during the write using paho.mqtt.publish.single(), but that does indeed carry more overhead because it’s not keeping the connection open between messages. I haven’t noticed it being that much of an issue though running 25hz winch data through there, and I can’t think of many other data sources that would be higher rate that would go through MQTT. Of course I’m running this on server grade hardware, so I’m not sure what the slowdown on a raspi would be.

THEN:

Some good news is I got into one of those brain modes where I can get a lot of things done in very short time and modified the writer so it works with paho mqtt APIs v2 and maintains a persistent connection until the object is destroyed. I also added some code  to check the version of pahoMQTT and make the appropriate changes. I tested with versions 2.1.0, 1.6.1, and 1.3.0, and they all seem to work without issue. I’ve attached the writer as a textfile, and hopefully our secure email gateway doesn’t dislike it.

**Comment by webbpinner** [comment]
What did the unittest come back with?

**Comment by davidpablocohn** [comment]
There's not actually an mqtt_writer unittest - it started breaking for
Lilly Petersen on the NBP.

**Comment by webbpinner** [comment]
...and when I read the issue I mistakenly thought MQTTReader.

**Comment by davidpablocohn** [comment]
Merged issue_395 to dev
